### PR TITLE
Fixed Menu structure to properly display and navigate all supported l…

### PR DESCRIPTION
**Pull request by Archangel35757**
Fixed Menu structure to properly display and navigate all supported levels-of-detail:  F1 (LOD1) thru F10 (LOD10).  Note:  Internally these are LOD0-9 (zero-based).

### CODE REVIEW

**Comment by Archangel35757** [comment]
[kyle2.zip](https://github.com/JACoders/OpenJK-Tools/files/4756091/kyle2.zip)
Here is a .GLM model file of Kyle having 10 LODs to verify the changes.

**Comment by Archangel35757** [comment]
Based on feedback from others... I'm going to change the LOD menu structure so it is a Cascading style (see attached image) and doesn't lengthen the parent menu.
modview_LODmenu_style... so do not approve yet.

**Comment by Archangel35757** [comment]
Ready for review/approval.

**Comment by Archangel35757** [comment]
Ready for review & approval.

**Comment by Archangel35757** [comment]
Changed fn declaration to private as requested.  Ready for review/approval.

**Review by xycaleth — APPROVED** [review]

**Comment by xycaleth** [comment]
All looks good!

**Comment by Archangel35757** [comment]
I plan to make some other improvements.

**Pull request merged**
